-- Raw inbox сообщений импорта КИЗ. Применять до включения KIZ import consumer.

BEGIN;

CREATE TABLE wms.kiz_import_messages (
    message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_at timestamptz NOT NULL DEFAULT now(),
    raw_body text NOT NULL,
    raw_payload jsonb,
    parse_status varchar(32) NOT NULL,
    parse_error text,
    order_guid text,
    supply_number text,
    wild_group_count integer NOT NULL DEFAULT 0,
    mark_code_count integer NOT NULL DEFAULT 0,
    exchange_name text,
    routing_key text,
    rabbit_message_id text,
    correlation_id text,
    headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_kiz_import_messages_parse_status
        CHECK (parse_status IN ('received', 'invalid_json')),
    CONSTRAINT chk_kiz_import_messages_counts
        CHECK (wild_group_count >= 0 AND mark_code_count >= 0)
);

CREATE INDEX idx_kiz_import_messages_received
    ON wms.kiz_import_messages (message_id DESC);

CREATE INDEX idx_kiz_import_messages_order_guid
    ON wms.kiz_import_messages (order_guid)
    WHERE order_guid IS NOT NULL;

COMMENT ON TABLE wms.kiz_import_messages IS
'Raw inbox сообщений импорта КИЗ из RabbitMQ без складских side effects.';

COMMIT;
