-- ============================================================================
-- WMS: пересортица между двумя product_id в одной direct-локации
--
-- Бизнес-смысл:
--   from_product_id: -Q
--   to_product_id:   +Q
--   Q всегда целое и > 0, net delta операции = 0.
--
-- Этот файл является точным DB-контрактом для сервисной реализации.
-- Не переименовывать таблицы, поля и константные значения без отдельного решения.
--
-- Перед применением:
--   1. Сделать backup / проверить stage.
--   2. Убедиться, что активна партиция wms.movements для текущей даты.
--   3. Применять до запуска новой версии WMS Service.
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- 1. Разрешить отдельный operation_code в общей allow-list таблице
-- --------------------------------------------------------------------------

ALTER TABLE wms.operation_locations
    DROP CONSTRAINT IF EXISTS chk_operation_locations_operation_code;

ALTER TABLE wms.operation_locations
    ADD CONSTRAINT chk_operation_locations_operation_code
    CHECK (
        operation_code IN (
            'kit_operations',
            're_sorting_operations'
        )
    );

COMMENT ON TABLE wms.operation_locations IS
'Список WMS-локаций, на которых разрешены доменные операции. '
'Поддерживаемые operation_code: kit_operations, re_sorting_operations.';

COMMENT ON COLUMN wms.operation_locations.operation_code IS
'Код доменной операции: kit_operations или re_sorting_operations.';

-- --------------------------------------------------------------------------
-- 2. Разрешить movement_type=re_sorting
--
-- Constraint на partitioned parent распространяется на partitions.
-- Сохраняется полный текущий список типов движения и добавляется re_sorting.
-- --------------------------------------------------------------------------

ALTER TABLE wms.movements
    DROP CONSTRAINT IF EXISTS chk_movement_type;

ALTER TABLE wms.movements
    ADD CONSTRAINT chk_movement_type
    CHECK (
        movement_type IN (
            'receive',
            'putaway',
            'transfer',
            'pick',
            'ship',
            'unpack',
            'adjust',
            'kit_assembly',
            'kit_disassembly',
            're_sorting'
        )
    );

COMMENT ON COLUMN wms.movements.movement_type IS
'receive, putaway, transfer, pick, ship, unpack, adjust, '
'kit_assembly, kit_disassembly, re_sorting.';

COMMENT ON COLUMN wms.movements.source_type IS
'Тип доменной операции-источника movement. '
'Для пересортицы: re_sorting_operation; для комплектации: kit_operation.';

COMMENT ON COLUMN wms.movements.source_id IS
'ID доменной операции-источника. '
'Для source_type=re_sorting_operation это wms.re_sorting_operations.operation_id.';

COMMENT ON COLUMN wms.movements.source_item_id IS
'ID строки детализации доменной операции. '
'Для source_type=re_sorting_operation это wms.re_sorting_operation_items.item_id.';

-- --------------------------------------------------------------------------
-- 3. Заголовок операции пересортицы
-- --------------------------------------------------------------------------

CREATE TABLE wms.re_sorting_operations (
    operation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    operation_location_id bigint NOT NULL,

    from_product_id character varying(50) NOT NULL,
    to_product_id character varying(50) NOT NULL,

    quantity integer NOT NULL,

    location_id bigint NOT NULL,
    location_code character varying(100) NOT NULL,

    reason text NOT NULL,
    author character varying(100) NOT NULL,

    status character varying(32) NOT NULL DEFAULT 'processing',
    error_message text,

    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

    created_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT chk_re_sorting_operation_products_different
        CHECK (from_product_id <> to_product_id),

    CONSTRAINT chk_re_sorting_operation_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_re_sorting_operation_reason
        CHECK (btrim(reason) <> ''),

    CONSTRAINT chk_re_sorting_operation_author
        CHECK (btrim(author) <> ''),

    CONSTRAINT chk_re_sorting_operation_status
        CHECK (status IN ('processing', 'completed', 'failed')),

    CONSTRAINT fk_re_sorting_operation_operation_location
        FOREIGN KEY (operation_location_id)
        REFERENCES wms.operation_locations(operation_location_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_re_sorting_operation_from_product
        FOREIGN KEY (from_product_id)
        REFERENCES public.products(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_re_sorting_operation_to_product
        FOREIGN KEY (to_product_id)
        REFERENCES public.products(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_re_sorting_operation_location
        FOREIGN KEY (location_id)
        REFERENCES wms.locations(location_id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE wms.re_sorting_operations IS
'Атомарные WMS-операции пересортицы: одинаковое целое количество физического '
'loose-остатка переносится между двумя разными product_id на одной разрешённой '
'direct-локации. 1С и RabbitMQ не вызываются.';

COMMENT ON COLUMN wms.re_sorting_operations.operation_location_id IS
'Ссылка на активную allow-list строку wms.operation_locations '
'с operation_code=re_sorting_operations и scope=direct.';

COMMENT ON COLUMN wms.re_sorting_operations.from_product_id IS
'Исходный SKU/product_id, physical loose-остаток которого уменьшается.';

COMMENT ON COLUMN wms.re_sorting_operations.to_product_id IS
'Целевой SKU/product_id, physical loose-остаток которого увеличивается.';

COMMENT ON COLUMN wms.re_sorting_operations.quantity IS
'Целое положительное количество. Одинаково для исходящего и входящего movement.';

COMMENT ON COLUMN wms.re_sorting_operations.location_id IS
'Точная direct-локация операции; subtree дочерних адресов не используется.';

COMMENT ON COLUMN wms.re_sorting_operations.location_code IS
'Кешированный код использованной локации для аудита. Источник истины — location_id.';

COMMENT ON COLUMN wms.re_sorting_operations.status IS
'processing, completed, failed. В MVP business validation/conflict обычно '
'откатывает transaction и не сохраняет failed operation, аналогично kit flow.';

-- --------------------------------------------------------------------------
-- 4. Две строки операции: source_outgoing и target_incoming
-- --------------------------------------------------------------------------

CREATE TABLE wms.re_sorting_operation_items (
    item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    operation_id bigint NOT NULL,

    role character varying(64) NOT NULL,
    product_id character varying(50) NOT NULL,
    quantity integer NOT NULL,

    movement_id bigint,
    movement_created_at timestamp with time zone,

    created_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT chk_re_sorting_operation_item_role
        CHECK (role IN ('source_outgoing', 'target_incoming')),

    CONSTRAINT chk_re_sorting_operation_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT uq_re_sorting_operation_item_role
        UNIQUE (operation_id, role),

    CONSTRAINT fk_re_sorting_operation_item_operation
        FOREIGN KEY (operation_id)
        REFERENCES wms.re_sorting_operations(operation_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_re_sorting_operation_item_product
        FOREIGN KEY (product_id)
        REFERENCES public.products(id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE wms.re_sorting_operation_items IS
'Детализация пересортицы. У completed operation должно быть две строки: '
'source_outgoing и target_incoming с одинаковым quantity.';

COMMENT ON COLUMN wms.re_sorting_operation_items.role IS
'source_outgoing = списание from_product_id; '
'target_incoming = приход to_product_id.';

COMMENT ON COLUMN wms.re_sorting_operation_items.movement_id IS
'ID movement, созданного для строки. FK не задаётся, поскольку partitioned '
'wms.movements не имеет устойчивой parent PK/unique модели.';

COMMENT ON COLUMN wms.re_sorting_operation_items.movement_created_at IS
'created_at соответствующего movement; используется вместе с movement_id '
'для поиска нужной partitioned movement row.';

-- --------------------------------------------------------------------------
-- 5. Индексы
-- --------------------------------------------------------------------------

CREATE INDEX idx_re_sorting_operations_created_at
    ON wms.re_sorting_operations (created_at DESC);

CREATE INDEX idx_re_sorting_operations_status_created_at
    ON wms.re_sorting_operations (status, created_at DESC);

CREATE INDEX idx_re_sorting_operations_from_product
    ON wms.re_sorting_operations (from_product_id);

CREATE INDEX idx_re_sorting_operations_to_product
    ON wms.re_sorting_operations (to_product_id);

CREATE INDEX idx_re_sorting_operations_location
    ON wms.re_sorting_operations (location_id);

CREATE INDEX idx_re_sorting_operations_operation_location
    ON wms.re_sorting_operations (operation_location_id);

CREATE INDEX idx_re_sorting_operation_items_operation
    ON wms.re_sorting_operation_items (operation_id);

CREATE INDEX idx_re_sorting_operation_items_product
    ON wms.re_sorting_operation_items (product_id);

CREATE INDEX idx_re_sorting_operation_items_movement
    ON wms.re_sorting_operation_items (movement_id)
    WHERE movement_id IS NOT NULL;

-- --------------------------------------------------------------------------
-- 6. updated_at
-- --------------------------------------------------------------------------

CREATE TRIGGER trg_re_sorting_operations_updated_at
BEFORE UPDATE ON wms.re_sorting_operations
FOR EACH ROW
EXECUTE FUNCTION wms.update_updated_at_column();

COMMIT;

-- ============================================================================
-- POST-APPLY READ-ONLY VERIFICATION
-- ============================================================================

-- 1. Новые объекты
SELECT
    to_regclass('wms.re_sorting_operations') AS operations_table,
    to_regclass('wms.re_sorting_operation_items') AS items_table;

-- 2. Проверить допустимые operation_code
SELECT pg_get_constraintdef(oid) AS operation_code_constraint
FROM pg_constraint
WHERE conrelid = 'wms.operation_locations'::regclass
  AND conname = 'chk_operation_locations_operation_code';

-- 3. Проверить допустимые movement_type
SELECT pg_get_constraintdef(oid) AS movement_type_constraint
FROM pg_constraint
WHERE conrelid = 'wms.movements'::regclass
  AND conname = 'chk_movement_type';

-- 4. Проверить таблицы/колонки/типы
SELECT
    table_schema,
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'wms'
  AND table_name IN (
      're_sorting_operations',
      're_sorting_operation_items'
  )
ORDER BY table_name, ordinal_position;

-- 5. Проверить constraints
SELECT
    c.conrelid::regclass AS table_name,
    c.conname,
    c.contype,
    pg_get_constraintdef(c.oid) AS definition
FROM pg_constraint c
WHERE c.conrelid IN (
    'wms.re_sorting_operations'::regclass,
    'wms.re_sorting_operation_items'::regclass
)
ORDER BY c.conrelid::regclass::text, c.conname;

-- 6. Проверить индексы
SELECT
    tablename,
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'wms'
  AND tablename IN (
      're_sorting_operations',
      're_sorting_operation_items'
  )
ORDER BY tablename, indexname;

-- ============================================================================
-- AUDIT QUERIES ДЛЯ ПОСЛЕДУЮЩЕГО ИСПОЛЬЗОВАНИЯ
-- ============================================================================

-- A. Completed operations без двух items
SELECT
    rso.operation_id,
    COUNT(rsoi.item_id) AS item_count
FROM wms.re_sorting_operations rso
LEFT JOIN wms.re_sorting_operation_items rsoi
       ON rsoi.operation_id = rso.operation_id
WHERE rso.status = 'completed'
GROUP BY rso.operation_id
HAVING COUNT(rsoi.item_id) <> 2;

-- B. Completed operations без обеих обязательных ролей
SELECT
    rso.operation_id,
    COUNT(*) FILTER (WHERE rsoi.role = 'source_outgoing') AS source_count,
    COUNT(*) FILTER (WHERE rsoi.role = 'target_incoming') AS target_count
FROM wms.re_sorting_operations rso
LEFT JOIN wms.re_sorting_operation_items rsoi
       ON rsoi.operation_id = rso.operation_id
WHERE rso.status = 'completed'
GROUP BY rso.operation_id
HAVING COUNT(*) FILTER (WHERE rsoi.role = 'source_outgoing') <> 1
    OR COUNT(*) FILTER (WHERE rsoi.role = 'target_incoming') <> 1;

-- C. Items без movement reference
SELECT *
FROM wms.re_sorting_operation_items
WHERE movement_id IS NULL
   OR movement_created_at IS NULL;

-- D. Items с отсутствующим movement
SELECT
    rsoi.*
FROM wms.re_sorting_operation_items rsoi
LEFT JOIN wms.movements m
       ON m.movement_id = rsoi.movement_id
      AND m.created_at = rsoi.movement_created_at
WHERE rsoi.movement_id IS NOT NULL
  AND m.movement_id IS NULL;

-- E. Несовпадение item/header quantity или product role
SELECT
    rso.operation_id,
    rso.from_product_id,
    rso.to_product_id,
    rso.quantity AS operation_quantity,
    rsoi.item_id,
    rsoi.role,
    rsoi.product_id,
    rsoi.quantity AS item_quantity
FROM wms.re_sorting_operations rso
JOIN wms.re_sorting_operation_items rsoi
  ON rsoi.operation_id = rso.operation_id
WHERE rsoi.quantity <> rso.quantity
   OR (
       rsoi.role = 'source_outgoing'
       AND rsoi.product_id <> rso.from_product_id
   )
   OR (
       rsoi.role = 'target_incoming'
       AND rsoi.product_id <> rso.to_product_id
   );

-- F. Movements с неверными source/type/side/quantity
SELECT
    rso.operation_id,
    rsoi.item_id,
    rsoi.role,
    m.movement_id,
    m.movement_type,
    m.product_id,
    m.from_location_id,
    m.to_location_id,
    m.quantity,
    m.source_type,
    m.source_id,
    m.source_item_id
FROM wms.re_sorting_operations rso
JOIN wms.re_sorting_operation_items rsoi
  ON rsoi.operation_id = rso.operation_id
JOIN wms.movements m
  ON m.movement_id = rsoi.movement_id
 AND m.created_at = rsoi.movement_created_at
WHERE m.movement_type <> 're_sorting'
   OR m.source_type <> 're_sorting_operation'
   OR m.source_id <> rso.operation_id
   OR m.source_item_id <> rsoi.item_id
   OR m.product_id <> rsoi.product_id
   OR m.quantity <> rso.quantity
   OR (
       rsoi.role = 'source_outgoing'
       AND (
           m.from_location_id IS DISTINCT FROM rso.location_id
           OR m.to_location_id IS NOT NULL
       )
   )
   OR (
       rsoi.role = 'target_incoming'
       AND (
           m.from_location_id IS NOT NULL
           OR m.to_location_id IS DISTINCT FROM rso.location_id
       )
   );

-- G. Completed operations с ненулевым net delta
WITH movement_deltas AS (
    SELECT
        rso.operation_id,
        CASE
            WHEN rsoi.role = 'source_outgoing' THEN -m.quantity
            WHEN rsoi.role = 'target_incoming' THEN  m.quantity
            ELSE 0
        END AS delta
    FROM wms.re_sorting_operations rso
    JOIN wms.re_sorting_operation_items rsoi
      ON rsoi.operation_id = rso.operation_id
    JOIN wms.movements m
      ON m.movement_id = rsoi.movement_id
     AND m.created_at = rsoi.movement_created_at
    WHERE rso.status = 'completed'
)
SELECT
    operation_id,
    SUM(delta) AS net_delta
FROM movement_deltas
GROUP BY operation_id
HAVING SUM(delta) <> 0;

-- H. Active allow-list пересортицы указывает на inactive location
SELECT
    ol.operation_location_id,
    ol.location_id,
    ol.location_code
FROM wms.operation_locations ol
JOIN wms.locations l
  ON l.location_id = ol.location_id
WHERE ol.operation_code = 're_sorting_operations'
  AND ol.scope = 'direct'
  AND ol.is_active = true
  AND l.is_active = false;
